CREATE TABLE song (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    original_key VARCHAR(255) NOT NULL,
    capo INTEGER,
    tempo INTEGER,
    difficulty VARCHAR(255),
    body TEXT,
    CONSTRAINT fk_song_artist FOREIGN KEY (artist_id) REFERENCES artist(id)
);